### ISSUE TITLE
Update to most recent server version (3.0.13.8)

### ISSUE THREAD

**Issue by seige404** [linuxserver/docker-gsm-ts3#17]
Hi,

would it be possible to include the most recent version of TS3 server in this docker? Afaik version 3.0.13.8 was released last summer.

Many thanks!

**Comment by sparklyballs** [comment]
on first run the container pulls the latest version available

you could try this (backup your appdata first just in case) after exec'ing in

s6-setuidgid abc /config/ts3server update

**Comment by seige404** [comment]
Thanks for the quick response, I tried the manual update but I get a lot of access denied errors and this:

Update available:
        Current build: 3.0.13.6 amd64
        Available build: 3.0.13.8 amd64


Applying update...
    fetching command_stop.sh...OK
[ FAIL ] Stopping ts3-server: Unable to stop TeamSpeak 3 Server
######################################################################## 100.0%
downloading teamspeak3-server_linux_amd64-3.0.13.8.tar.bz2...OK
extracting teamspeak3-server_linux_amd64-3.0.13.8.tar.bz2...OK
copying to /config/serverfiles...cp: cannot create regular file '/config/serverfiles/ts3server': Text file busy
FAIL
[ INFO ] Starting ts3-server: TeamSpeak 3 Server is already running
[  OK  ] Starting ts3-server: TeamSpeak 3 Server
root@Tower:/#

**Comment by seige404** [comment]
I found a solution, albeit not a very elegant one.

I stopped the server and extracted the downloaded server file into the appdata folder of teamspeak, overwriting duplicates. This worked. A more elegant solution would be much appreciated, however. :)

Thank you for your help!
