### ISSUE TITLE
Version of teamspeak on server won't let clients on 3.2 connect.

### ISSUE THREAD

**Issue by defib** [linuxserver/docker-gsm-ts3#24]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

**Comment by greg2895** [comment]
I am also having the same issue with windows client 3.2.0 [Stable].

Disconnected from server (server version is too old for command)

**Comment by IncognitoCore** [comment]
I was still running 3.0.13.8 and had the same issue.

As mentioned in another issue (https://github.com/linuxserver/docker-gsm-ts3/issues/17), the newest available server version will be downloaded upon first creation.

I've found the steps on how to upgrade a TeamSpeak server [on the TeamSpeak forum](https://forum.teamspeak.com/threads/123827-How-to-Update-Upgrade-server).

The steps on how I've managed to update the server within the Docker container are as follows:
1. Shut down the server (shutdown the docker).
2. Download the correct server version [here](https://www.teamspeak.com/en/downloads#server).
3. **Merge** the downloaded files with the existing files in /config/serverfiles.
4. Start the server (could take some time).

Note: if you follow these steps, make sure you backup the full /config directory for if anything goes wrong before step 3.

**Comment by defib** [comment]
After doing step 3, the server was reset to brand new. What files are the settings that I should not overwrite?

**Comment by IncognitoCore** [comment]
I've editted step 3 to better describe what I did: merging instead of replacing. I've used the rsync command to merge the downloaded files with the existing server files.

`rsync -a /mnt/user/data/teamspeak3-server_linux_amd64-3.3.0/* /mnt/user/appdata/teamspeak3/serverfiles/`

This should keep your settings (like channels, history, known clients, passwords, ect).

**Comment by defib** [comment]
After running that command, I fail to connect and this is appearing in the log:

`[33mWarning![0m abc does not have sudo access. Manually install dependencies.
sudo dpkg --add-architecture i386; sudo apt-get install lib32gcc1 libstdc++6:i386`

Even after doing as it asked, now I get nothing in the logs, but still failed to connect

**Comment by IncognitoCore** [comment]
I'm not sure what did go wrong for your installation. Maybe someone with some more linux knowledge or one of the creators of this repo could help you out.

**Comment by sparklyballs** [comment]
stop and delete the container, remove any hanging images 

backup your config.

repull a new image and run a new container.

then try this command 

docker exec -it -u abc <container name>  /bin/bash -c '/config/ts3server update'

substituting <container name> for what you have called the container

**Comment by sparklyballs** [comment]
if it works, restart the container

**Comment by defib** [comment]
`docker exec -it -u abc teamspeak3 /bin/bash -c '/config/ts3server update'`
`[ .... ] Update ts3-server:     fetching update_ts3.sh...OK
[ .... ] Update ts3-server: Checking for update: teamspeak.comfind: ‘./etc/s6/services/s6-fdholderd
/supervise’: Permission denied
find: ‘./etc/ssl/private’: Permission denied
find: ‘./proc/tty/driver’: Permission denied
find: ‘./proc/1/task/1/fd’: Permission denied
find: ‘./proc/1/task/1/fdinfo’: Permission denied
find: ‘./proc/1/task/1/ns’: Permission denied
find: ‘./proc/1/fd’: Permission denied
find: ‘./proc/1/map_files’: Permission denied
find: ‘./proc/1/fdinfo’: Permission denied
find: ‘./proc/1/ns’: Permission denied
find: ‘./proc/44/task/44/fd’: Permission denied
find: ‘./proc/44/task/44/fdinfo’: Permission denied
find: ‘./proc/44/task/44/ns’: Permission denied
find: ‘./proc/44/fd’: Permission denied
find: ‘./proc/44/map_files’: Permission denied
find: ‘./proc/44/fdinfo’: Permission denied
find: ‘./proc/44/ns’: Permission denied
find: ‘./proc/214/task/214/fd’: Permission denied
find: ‘./proc/214/task/214/fdinfo’: Permission denied
find: ‘./proc/214/task/214/ns’: Permission denied
find: ‘./proc/214/fd’: Permission denied
find: ‘./proc/214/map_files’: Permission denied
find: ‘./proc/214/fdinfo’: Permission denied
find: ‘./proc/214/ns’: Permission denied
find: ‘./root’: Permission denied
find: ‘./run/s6/services/s6-fdholderd/supervise’: Permission denied
find: ‘./run/s6/services/s6-fdholderd/event’: Permission denied
find: ‘./run/s6/services/teamspeak/event’: Permission denied
find: ‘./run/s6/services/teamspeak/supervise’: Permission denied`

It then hangs there

**Comment by greg2895** [comment]
I can confirm that the following steps worked on ubuntu 18.04:
Make a backup of your ts files first!
```
docker stop <ts_container_name>

wget http://dl.4players.de/ts/releases/3.3.0/teamspeak3-server_linux_amd64-3.3.0.tar.bz2

tar -vxjf teamspeak3-server_linux_amd64-3.3.0.tar.bz2

rsync -a teamspeak3-server_linux_amd64/* /<path_to_ts>/serverfiles/

docker start <ts_container_name>
```
Confirm that ts started correctly:
docker logs -f <ts_container_name>

**Comment by defib** [comment]
I am still getting the `abc does not have sudo access. Manually install dependencies. sudo dpkg --add-architecture i386; sudo apt-get install lib32gcc1 libstdc++6:i386` but after attempting to connect a second time, I get in. Thank you for all your help!
